### PR TITLE
Update libraries

### PR DESCRIPTION
**Pull request by jochenberger**
Updated de.flapdoodle.embed.mongo and org.mongodb:mongo-java-driver.

### CODE REVIEW

**Comment by jochenberger** [comment]
Btw, is there a chance for a release anytime soon?

**Comment by roberttaylor426** [comment]
Sure, I'll cut a release today.

**Comment by jochenberger** [comment]
Great, thanks.

**Comment by roberttaylor426** [comment]
Just pushed 0.9.0 to central. It should be available within an hour or two.

**Pull request merged**
