### PR TITLE
Add config option for proxy url and port

### LINKED ISSUE #28: Gradle proxy settings seem to be ignored
I'm using the Gradle Mongo Plugin in a corporate environment, behind a firewall.

My gradle.properties file contains all the 'systemProp.https.proxy' values I need, normally.

In the buildscript dependencies, I've add this line, defining the internal maven url, under 'mavenCentral()':

``` sh
maven { url 'http://...' }
```

and the classpath dependency matches the latest version available there:

``` sh
classpath 'com.sourcemuse.gradle.plugin:gradle-mongo-plugin:0.8.0'
```

When I run 'gradle tasks', I do see startManagedMongoDb/startMongoDb/stopMongoDb among the output.

But when I try 'gradle startManagedMongoDb' or 'gradle startMongoDb', I get this error, which is b/c of no access to <tt>http://fastdl.mongodb.org/</tt>:

``` sh
:startMongoDb
Downloading Mongo 2.4.3 distribution...
prepare executable
java.io.IOException: Could not open inputStream for http://fastdl.mongodb.org/linux/mongodb-linux-x86_64-2.4.3.tgz
        at de.flapdoodle.embed.process.store.Downloader.downloadInputStream(Downloader.java:131)
...
```

So is there something explicit I need to do in my gradle build file, above and beyond having proxy settings in gradle.properties?

### PR DESCRIPTION
**Pull request by arudge**
This should resolve #28.

### CODE REVIEW

**Comment by roberttaylor426** [comment]
Great work, thanks Andy.

What do you think about testing that this actually works? One possibility might be to add a couple of tests to the [MongoPluginConfigSpec](https://github.com/sourcemuse/GradleMongoPlugin/blob/master/src/test/groovy/com/sourcemuse/gradle/plugin/MongoPluginConfigSpec.groovy) to verify that when the proxy is running and we try to use it the download is successful, and if the proxy is not running there is a build exception. That should give us confidence at least that the proxy is being used. What do you think?

We could use a library like [LittleProxy](https://github.com/adamfisk/LittleProxy) to facilitate such tests.

**Comment by arudge** [comment]
Good call on the functional test with an external proxy, I had missed something. 
I've also added support for `artifactStorePath`.

**Comment by roberttaylor426** [comment]
Nice one, thanks. I'm going to merge this.

Before I release I'm going to make further minor change: the `downloadURL` property that was introduced in a previous PR violated the existing naming convention, it should have been `downloadUrl` (in the same form as `bindIp`). Thanks for bringing it to my attention by updating the README. :-)

**Comment by arudge** [comment]
Awesome thanks for the merge. 
Naming things is hard. I went back between both `URL` and `Url` too many times.

**Comment by roberttaylor426** [comment]
It certainly is.

I don't really have much of a preference either, but since we went lowercase on the 'p' in `bindIp` we should at least be consistent. :-)

**Comment by roberttaylor426** [comment]
Btw, any objections to me making this the 1.0.0 release?

**Comment by arudge** [comment]
nope.

**Comment by roberttaylor426** [comment]
Released as 1.0.0.

**Pull request merged**
